const pets = [
    {
      pet: 'gatos',
      pets: [
        {
          id: '1',
          name: 'Lily',
          image: require('../assets/cat1.jpg'),
          age: '5 anos',
          gender: 'female',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          description: 'Foi encontrado no bairro Tal após recentes enchentes, assustado e buscando um lugar seguro. É um gato brasino, se encontra no abrigo Teste, qualquer coisa entrar em contato.',
          diaEncontrado: '25 de Maio de 2024',
        },
        {
          id: '2',
          name: 'Lucy',
          image: require('../assets/cat2.jpg'),
          age: '2 anos',
          gender: 'female',
          location: 'R. Teste Teste, 126 - Conventos, Lajeado - RS',
          description: 'Gato da raça tal, encontrado em tal lugar',
          diaEncontrado: '30 de Maio de 2024',
        },
        {
          id: '3',
          name: 'Nala',
          image: require('../assets/cat3.jpg'),
          age: '2 anos',
          gender: 'female',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          description: 'Gato da raça tal, encontrado em tal lugar',
          diaEncontrado: '25 de Maio de 2024',
        },
        {
          id: '4',
          name: 'Simba',
          image: require('../assets/cat4.jpg'),
          age: '2 anos',
          gender: 'female',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          description: 'Gato da raça tal, encontrado em tal lugar',
          diaEncontrado: '25 de Maio de 2024',
        },
      ],
    },
    {
      pet: 'cachorros',
      pets: [
        {
          id: '1',
          name: 'Bally',
          image: require('../assets/dog1.jpg'),
          age: '2 anos',
          gender: 'male',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          description: 'Cachorro da raça tal, encontrado em tal lugar',
          diaEncontrado: '25 de Maio de 2024',
        },
        {
          id: '2',
          name: 'Max',
          image: require('../assets/dog2.jpg'),
          age: '2 anos',
          gender: 'male',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          description: 'Cachorro da raça tal, encontrado em tal lugar',
          diaEncontrado: '25 de Maio de 2024',
        },
      ],
    },
    {
      pet: 'aves',
      pets: [
        {
          id: '1',
          name: 'Coco',
          image: require('../assets/bird1.jpg'),
          age: '2 anos',
          gender: 'female',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          description: 'Teste de descrição para aves',
          diaEncontrado: '25 de Maio de 2024',
        },
        {
          id: '2',
          name: 'Alfie',
          image: require('../assets/bird2.jpg'),
          age: '4 anos',
          gender: 'male',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          description: 'Teste de descrição para aves',
          diaEncontrado: '25 de Maio de 2024',
        },
      ],
    },
    {
      pet: 'coelhos',
      pets: [
        {
          id: '1',
          name: 'Boots',
          image: require('../assets/bunny1.jpg'),
          age: '1 anos',
          gender: 'male',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          description: 'Teste de descrição para coelhos',
          diaEncontrado: '25 de Maio de 2024',
        },
        {
          id: '2',
          name: 'Pookie',
          image: require('../assets/bunny2.jpg'),
          age: '1 anos',
          gender: 'female',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          description: 'Coelho da raça tal, encontrado em tal lugar',
          diaEncontrado: '25 de Maio de 2024',
        },
      ],
    },
    {
      pet: 'outros',
      pets: [
        {
          id: '1',
          name: 'Peanut',
          image: require('../assets/other1.jpg'),
          age: '1 anos',
          gender: 'male',
          location: 'R. Elizabeth Beuren, 125 - Conventos, Lajeado - RS',
          diaEncontrado: '25 de Maio de 2024',
        },
      ],
    },
  ];
  
  export default pets;